In [10]:
import numpy as np

sales = [[10,20,30,40],[11,12,13,14]] # must be of equal length
sales_np_array = np.array(sales)

print(sales_np_array)
print(sales_np_array.dtype)
print(sales_np_array.size) # total number of elements in all the dimentions
print(sales_np_array.shape) # the structure of the array

sales_np_array + 1

[[10 20 30 40]
 [11 12 13 14]]
int64
8
(2, 4)


array([[11, 21, 31, 41],
       [12, 13, 14, 15]])

In [11]:
from numpy.random import default_rng

rng = default_rng(12345)
arr = rng.random(10)

arr