In [10]:
import numpy as np

sales = [[10,20,30,40],[11,12,13,14]] # must be of equal length
sales_np_array = np.array(sales)

print(sales_np_array)
print(sales_np_array.dtype)
print(sales_np_array.size) # total number of elements in all the dimentions
print(sales_np_array.shape) # the structure of the array

sales_np_array + 1

[[10 20 30 40]
 [11 12 13 14]]
int64
8
(2, 4)


array([[11, 21, 31, 41],
       [12, 13, 14, 15]])

In [12]:
from numpy.random import default_rng

rng = default_rng(12345)
arr = rng.random(10)

arr

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [18]:
from numpy.random import default_rng

rng = default_rng(12345)
random_ages = rng.integers(1,100,100).reshape(10,10)
print(random_ages)

[[70 23 79 32 21 79 64 67 98 39]
 [84 33 57 60 22 19 23 67 61 94]
 [70 25 91 94 73 67 13 10 27 44]
 [ 8 88 47 70 22 33 12 73 77 22]
 [71  9 39 16 74 34 47 47 48 27]
 [56 81 50 20  3 13  9 10 13 60]
 [80 85 65 60 33 93 64 72 73 86]
 [70 93 54 55 25 93 55 50 32 28]
 [63 45 57 66 90 33 68 90 46 26]
 [29 34 63 26 84 36  7  1  3 63]]
